routes/web.php
<?php

// determine the language
$lang = Request::server('HTTP_ACCEPT_LANGUAGE');
if( isset( explode(',', $lang)[0] ) )
{
	App::setLocale( explode(',', $lang)[0] );
}

App::setLocale('de');

Auth::routes();

// Player
// the player does not have to be authorized to access the character sheet and group
Route::group(['middleware' => ['playerAccess']], function() {
	// TODO: were player specific views -> now user specific
	// Route::resource('group/{group}/player/{player}/file', 'Companion\PlayerFileController');
	// Route::resource('group/{group}/player/{player}/character', 'Companion\CharacterController');
	// Route::post('group/{group}/player/{player}/character/{characterId}/set-active', 'Companion\CharacterController@setActive') -> name('character.make_active');
});

// HomeController determines which view should be rendered
Route::get('/', 'HomeController@index') -> name('home');


// all frontend routes
Route::group( [], function(){
  Route::get('register', function(){ 
    return view('public.register'); 
  }) -> name('register');
	Route::get('privacy-policy', function(){
		return view('public.privacy_policy');
	}) -> name('privacy-policy');
	Route::get('imprint', function(){
		return view('public.imprint');
	}) -> name('imprint');
	Route::get('features', 'HomeController@showFeatures');
});


// all backend routes for the companion app are protected
Route::group(['middleware' => ['auth']], function () {

	// Logout
	Route::get('logout', function(){
		Auth::logout();
		return redirect('/');
	}) -> name('logout');

  Route::resource('user', 'Companion\UserProfileController');
  Route::post('user/{user}/changePassword', 'Companion\UserProfileController@changePassword') -> name('user.change_password');
	

  Route::get('files/{file}/download', 'Companion\FileController@download') -> name('files.download');
  Route::delete('files/{file}', 'Companion\FileController@destroy') -> name('files.destroy');
	
  // Group
  Route::resource('group', 'Companion\GroupController');

  // Group.* routes
  Route::name('group.')->middleware('can:view,group')->group( function(){

    // Group
		Route::post('group/{group}/invite-user', 'Companion\GroupController@inviteUser') -> name('invite_user');
		Route::post('group/{group}/remove-player', 'Companion\GroupController@removePlayer') -> name('remove_player');

    Route::resource('group/{group}/game-system', 'Companion\GroupGameSystemController') -> only(['update']);

    // TODO!!!
    // accept and reject need to be POST methods!
    Route::name('invitation.')->group( function() {
      Route::get('group/{group}/invitation/{groupInvitation}/accept', 'Companion\GroupInvitationController@accept')->name('accept');
  		Route::get('group/{group}/invitation/{groupInvitation}/reject', 'Companion\GroupInvitationController@reject')->name('reject');
      Route::delete('group/{group}/invitation/{groupInvitation}/destroy', 'Companion\GroupInvitationController@destroy')->name('destroy');
    });

    // Group Users
    // Route::resource('group/{group}/character', 'Companion\GroupCharacterController');
    Route::resource('group/{group}/user', 'Companion\GroupUserController') -> only(['show', 'index', 'destroy']);

    Route::get('group/{group}/characters', 'Companion\GroupController@showCharacters') -> name('characters');

    Route::get('group/{group}/user/{user}/character', 'Companion\GroupCharacterController@show') -> name('character');
    Route::put('group/{group}/user/{user}/character', 'Companion\GroupCharacterController@update') -> name('character.update');

    // Characters
    Route::name('character.')->group( function() {

      // Characters
      Route::resource('group/{group}/character/{character}/file', 'Companion\GroupCharacterFileController') -> only(['store', 'show', 'destroy']);
      Route::name('file.')->group( function() {
        // Character Files
        Route::get('group/{group}/character/{character}/file/{file}/download', 'Companion\GroupCharacterFileController@download') -> name('download');
      });

    });

  });
	

	// User Settings
	// Route::resource('user', 'Companion\UserProfileController');

});

app/Http/Controllers/Companion/GroupCharacterController.php
<?php

namespace App\Http\Controllers\Companion;

use Illuminate\Http\Request;
use App\Group;
use App\User;
use App\Character;
use App\Http\Controllers\Controller;

class GroupCharacterController extends Controller
{

  public function show(Request $request, Group $group, User $user)
  {
    $character = Character::firstOrNew(['user_id' => $user->id, 'group_id' => $group->id]);

    $this -> authorize('view', $group);
    if( !empty( $character -> additional_data ) )
    {
      $character -> additional_data = json_decode($character -> additional_data, true);
    }

    $files = $character -> files;
    $characterSheet = null;

    $files = $files -> filter(function ($value, $key) use ($characterSheet) {
      if( $value -> file_type == config('tablegamers.file_types.character_sheet') )
      {
        $characterSheet = $value;
        return false;
      }
    });

    if( auth() -> id() == $user -> id )
    {
      return view('companion.group_character.character_edit') -> with(compact('group', 'character', 'files'));
    }
    return view('companion.group_character.character') -> with(compact('group', 'character', 'files', 'characterSheet'));
  }

  public function update(Request $request, Group $group)
  {
    $request -> validate([
      'name' => 'required|max:255',
      'image' => 'image|max:5000',
      'gender' => 'max:255',
      'age' => 'nullable|integer',
      'race' => 'max:255',
      'classname' => 'max:255',
    ]);

    $character = Character::firstOrCreate(['user_id' => auth()->user()->id, 'group_id' => $group -> id]);
    $character -> fill( $request -> all() );

    // collect additional data from request
    $requestData = $request -> all();
    unset($requestData['_token']);
    unset($requestData['_method']);
    $requestDataJson = json_encode($requestData);
    $character -> additional_data = $requestDataJson;

    if( $request -> has('image') ){
      $path = $request -> image -> store('character_images', 'public');
      $character -> image = $path;
    }

    $character -> save();
    return back();
  }
}

resources/views/companion/group_character/partials/character_edit_form_files.blade.php
<div class="card mb-4">
  <div class="card-body">
    <h2 class="h5">@lang('character.character_files')</h2>
    <p class="text-muted">
      Hier kannst du alle sonstigen Dateien zu deinem Charakter hinzufügen.
    </p>
    
    <div class="row">


      @foreach($files as $file)
        <div class="col-md-6">
          @include('shared.file', ['fileName' => $file -> name, 
          'fileCreatedAt' => $file -> created_at, 
          'fileShowLink' => route('group.character.file.show', [$group, $currentCharacter, $file]), 
          'fileDownloadLink' => route('group.character.file.download', [$group, $currentCharacter, $file]), 
          'fileDeleteLink' => route('group.character.file.destroy', [$group, $currentCharacter, $file]) ])
        </div>
      @endforeach
    </div>

    <form action="{{ route('group.character.file.store', [$group, $currentCharacter]) }}" class="mt-2" method="POST" id="fileUploadForm" enctype="multipart/form-data">
      @csrf

      <div class="form-row">
        <div class="form-group col">
          <input type="text" name="name" value="{{old('name')}}" class="form-control form-control-sm" placeholder="Name">
        </div>
        <div class="form-group col">
          <input type="file" name="file" class="form-control-file form-control-sm">
        </div>
      </div>

      @include('shared.errors')

      <button type="submit" class="btn btn-primary">{{ __('character.character_add_file') }}</button>
    </form>
  </div>
</div>

resources/views/companion/group_character/partials/delete_character_modal.blade.php
@component('shared.modal', ['id' => 'character-destroy-'.$character->id, 'formUrl' => route('group.character.destroy', [$group, $character]), 'formMethod' => 'DELETE', 'confirmation' => __('character.delete_confirmation_button'), 'title' => __('character.delete_confirmation_title')])
      @lang('character.delete_confirmation', ['name' => $character->name])
@endcomponent