routes/web.php
<?php

// determine the language
$lang = Request::server('HTTP_ACCEPT_LANGUAGE');
if( isset( explode(',', $lang)[0] ) )
{
	App::setLocale( explode(',', $lang)[0] );
}

App::setLocale('de');

Auth::routes();

// Player
// the player does not have to be authorized to access the character sheet and group
Route::group(['middleware' => ['playerAccess']], function() {
	// TODO: were player specific views -> now user specific
	// Route::resource('group/{group}/player/{player}/file', 'Companion\PlayerFileController');
	// Route::resource('group/{group}/player/{player}/character', 'Companion\CharacterController');
	// Route::post('group/{group}/player/{player}/character/{characterId}/set-active', 'Companion\CharacterController@setActive') -> name('character.make_active');
});

// HomeController determines which view should be rendered
Route::get('/', 'HomeController@index') -> name('home');


// all frontend routes
Route::group( [], function(){
  Route::get('register', function(){ 
    return view('public.register'); 
  }) -> name('register');
	Route::get('privacy-policy', function(){
		return view('public.privacy_policy');
	}) -> name('privacy-policy');
	Route::get('imprint', function(){
		return view('public.imprint');
	}) -> name('imprint');
	Route::get('features', 'HomeController@showFeatures');
});


// all backend routes for the companion app are protected
Route::group(['middleware' => ['auth']], function () {

	// Logout
	Route::get('logout', function(){
		Auth::logout();
		return redirect('/');
	}) -> name('logout');

  Route::resource('user', 'Companion\UserProfileController');
  Route::post('user/{user}/changePassword', 'Companion\UserProfileController@changePassword') -> name('user.change_password');
	

  Route::get('files/{file}/download', 'Companion\FileController@download') -> name('files.download');
  Route::delete('files/{file}', 'Companion\FileController@destroy') -> name('files.destroy');
	
  // Group
  Route::resource('group', 'Companion\GroupController');

  // Group.* routes
  Route::name('group.')->middleware('can:view,group')->group( function(){

    // Group
		Route::post('group/{group}/invite-user', 'Companion\GroupController@inviteUser') -> name('invite_user');
		Route::post('group/{group}/remove-player', 'Companion\GroupController@removePlayer') -> name('remove_player');

    Route::resource('group/{group}/game-system', 'Companion\GroupGameSystemController') -> only(['update']);

    // TODO!!!
    // accept and reject need to be POST methods!
    Route::name('invitation.')->group( function() {
      Route::get('group/{group}/invitation/{groupInvitation}/accept', 'Companion\GroupInvitationController@accept')->name('accept');
  		Route::get('group/{group}/invitation/{groupInvitation}/reject', 'Companion\GroupInvitationController@reject')->name('reject');
      Route::delete('group/{group}/invitation/{groupInvitation}/destroy', 'Companion\GroupInvitationController@destroy')->name('destroy');
    });

    // Group Users
    // Route::resource('group/{group}/character', 'Companion\GroupCharacterController');
    Route::resource('group/{group}/user', 'Companion\GroupUserController') -> only(['show', 'index', 'destroy']);

    Route::get('group/{group}/characters', 'Companion\GroupController@showCharacters') -> name('characters');

    Route::get('group/{group}/user/{user}/character', 'Companion\GroupCharacterController@show') -> name('character');
    Route::put('group/{group}/user/{user}/character', 'Companion\GroupCharacterController@update') -> name('character.update');

    // Characters
    Route::name('character.')->group( function() {

      // Characters
      Route::resource('group/{group}/character/{character}/file', 'Companion\GroupCharacterFileController') -> only(['store', 'show', 'destroy']);
      Route::name('file.')->group( function() {
        // Character Files
        Route::get('group/{group}/character/{character}/file/{file}/download', 'Companion\GroupCharacterFileController@download') -> name('download');
      });

    });

  });
	

	// User Settings
	// Route::resource('user', 'Companion\UserProfileController');

});

app/Http/Controllers/Api/GroupController.php
<?php

namespace App\Http\Controllers\Api;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class GroupController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return \App\Group::get();
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Companion/FileController.php
<?php

namespace App\Http\Controllers\Companion;

use App\File;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;

class FileController extends Controller
{
  public function download(Request $request, File $file)
  {
    return Storage::disk('public')->download($file->path);
  }

  public function show(Request $request, File $file)
  {
    return response() -> file( Storage::disk('public')->path($file->path) );
  }

  public function destroy(Request $request, File $file)
  {
    $file -> delete();
    return back();
  }
}

app/Http/Controllers/Companion/GroupCharacterController.php
<?php

namespace App\Http\Controllers\Companion;

use Illuminate\Http\Request;
use App\Group;
use App\User;
use App\Character;
use App\Http\Controllers\Controller;

class GroupCharacterController extends Controller
{

  public function show(Request $request, Group $group, User $user)
  {
    $character = Character::firstOrNew(['user_id' => $user->id, 'group_id' => $group->id]);

    $this -> authorize('view', $group);
    if( !empty( $character -> additional_data ) )
    {
      $character -> additional_data = json_decode($character -> additional_data, true);
    }

    $files = $character -> files;
    $characterSheet = null;

    $files = $files -> filter(function ($value, $key) use ($characterSheet) {
      if( $value -> file_type == config('tablegamers.file_types.character_sheet') )
      {
        $characterSheet = $value;
        return false;
      }
    });

    if( auth() -> id() == $user -> id )
    {
      return view('companion.group_character.character_edit') -> with(compact('group', 'character', 'files'));
    }
    return view('companion.group_character.character') -> with(compact('group', 'character', 'files', 'characterSheet'));
  }

  public function update(Request $request, Group $group)
  {
    $request -> validate([
      'name' => 'required|max:255',
      'image' => 'image|max:5000',
      'gender' => 'max:255',
      'age' => 'nullable|integer',
      'race' => 'max:255',
      'classname' => 'max:255',
    ]);

    $character = Character::firstOrCreate(['user_id' => auth()->user()->id, 'group_id' => $group -> id]);
    $character -> fill( $request -> all() );

    // collect additional data from request
    $requestData = $request -> all();
    unset($requestData['_token']);
    unset($requestData['_method']);
    $requestDataJson = json_encode($requestData);
    $character -> additional_data = $requestDataJson;

    if( $request -> has('image') ){
      $path = $request -> image -> store('character_images', 'public');
      $character -> image = $path;
    }

    $character -> save();
    return back();
  }
}

app/Http/Controllers/Companion/GroupCharacterFileController.php
<?php

namespace App\Http\Controllers\Companion;

use App\Character;
use App\CharacterFile;
use App\Group;
use App\File;
use App\Http\Controllers\Controller;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Illuminate\Validation\Rule;

class GroupCharacterFileController extends Controller
{
    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request, Group $group, Character $character)
    {
      $request -> validate([
        'file' => 'required|file|max:5000',
        'name' => 'required|max:255',
        'file_type' => [
          'required',
          Rule::in(config('tablegamers.file_types')),
        ]
      ]);

      // store the file
      if( $request -> has('file') )
      {
        $path = $request -> file -> store('character_files', 'public');
        $file = new File();
        $file -> uploader_user_id = $character -> user -> id;
        $file -> name = $request -> name;
        $file -> mime_type = $request -> file -> getMimeType();
        $file -> path = $path;

        $character -> files() -> save($file, ['file_type' => $request -> file_type]);

        return back() -> with(['success' => 'File uploaded successful']);
      }
      return back() -> with(['error' => 'Nope!']);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Request $request, Group $group, Character $character, CharacterFile $file)
    {
      $characterFile = Storage::disk('public')->path($file -> filename);
      return response()->file($characterFile);
    }

    /**
     *  Download a specific character file
     *
     */
    public function download(Request $request, Group $group, Character $character, CharacterFile $file)
    {
      return Storage::disk('public')->download($file -> filename);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request, Group $group, Character $character, CharacterFile $file)
    {
      $file -> delete();
      return back();
    }
}

app/Http/Controllers/Companion/GroupController.php
<?php

namespace App\Http\Controllers\Companion;

use App\Character;
use App\GameSystem;
use App\Group;
use App\GroupGameSystem;
use App\GroupInvitation;
use App\Http\Controllers\Controller;
use App\Models\Misc\GroupProgress;
use App\Notifications\GroupInvitationMail;
use App\Player;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Gate;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Facades\Notification;
use Illuminate\Support\Facades\Storage;
use Illuminate\Validation\Rule;
use Validator;

class GroupController extends Controller
{

  /**
   * Show the form for creating a new resource.
   *
   * @return \Illuminate\Http\Response
   */
  public function create()
  {
    $gameSystems = GameSystem::get();
    return view('companion.group.group_create') -> with(compact('gameSystems'));
  }

  /**
   * Store a newly created resource in storage.
   *
   * @param  \Illuminate\Http\Request  $request
   * @return \Illuminate\Http\Response
   */
  public function store(Request $request)
  {
    $request->validate([
      'name' => 'required|max:255'
    ]);

    $group = new Group;
    $group -> name = $request -> name;
    $group -> save();

    GroupGameSystem::create(['group_id' => $group -> id, 'is_custom_system' => true, 'game_system_id' => config('tablegamers.game_system_default_id')]);

    // intermediate table
    Auth::user()->groups()->attach($group, ['is_admin' => true]);

    return redirect() -> route('home');
  }

  /**
   * Display the specified resource.
   *
   * @param  int  $id
   * @return \Illuminate\Http\Response
   */
  public function show(Group $group, $playerIdentifier = null)
  {
    $this -> authorize('view', $group);
    // if( Gate::denies('view', $group) )
    // {
    //   // Show the "this group is private message"
    //   return view('companion.group.group_private') -> with(compact(['group']));
    // }

    $group -> load(['users', 'characters', 'system']);
    $isGroupAdmin = Auth::user()->isGroupAdmin( $group -> id );

    // calculate group progress
    $progress = new GroupProgress();
    $progress -> calculate($group, auth()->user(), auth()->user()->can('edit', $group));

    return view('companion.group.group')->with(compact(['group', 'isGroupAdmin', 'progress']));
  }

  /**
   * Show the form for editing the specified resource.
   *
   * @param  int  $id
   * @return \Illuminate\Http\Response
   */
  public function edit(Group $group)
  {
    $this -> authorize('edit', $group);
    $gameSystems = GameSystem::get();

    return view('companion.group.group_edit')->with(compact('group', 'gameSystems'));
  }

  /**
   * Update the specified resource in storage.
   *
   * @param  \Illuminate\Http\Request  $request
   * @param  int  $id
   * @return \Illuminate\Http\Response
   */
  public function update(Request $request, Group $group)
  {
    $this -> authorize('edit', $group);
    $request->validate([
      'name' => 'required|max:255',
      'image' => 'image|max:5000',
      // 'next_session_datetime' => 'date',
      'next_session_location' => 'max:255',
      'is_private' => 'boolean',
    ]);

    // find the group and update the values
    $group -> name = $request -> name;
    $group -> description = $request -> description;

    $group -> next_session_datetime = $request -> next_session_datetime;
    $group -> next_session_location = $request -> next_session_location;

    // TODO: If public groups are supported, this needs to be adjusted!
    $group -> is_private = true;

    // store the image
    if( $request -> has('image') ){
      $path = $request -> image -> store(config('tablegamers.group_images_folder'), 'public');
      $group -> image = $path;
    }

    $group -> save();

    return redirect()->route('group.show', [$group->id]);
  }

  /**
   * Remove the specified resource from storage.
   *
   * @param  int  $id
   * @return \Illuminate\Http\Response
   */
  public function destroy(Group $group)
  {
    $this -> authorize('edit', $group);

    $group -> delete();

    return redirect() -> route('home');
  }

  public function showCharacters(Request $request, Group $group)
  {
    $this -> authorize('view', $group);

    $usersWithoutCharacter = $group -> users() -> whereDoesntHave('characters', function($query) use ($group){
      $query -> where('group_id', $group->id);
    }) -> get();

    // sort users so that the current authenticated user is first
    $usersWithoutCharacter = $usersWithoutCharacter -> sortBy(function ($user, $key) {
      if( $user -> id == auth()->id() )
        return -1;
      else
        return $user['name'];
      });

    $characters = $group -> characters;

    return view('companion.group.group_characters')->with(compact('group', 'characters', 'usersWithoutCharacter'));
  }

  public function inviteUser(Request $request, Group $group)
  {
    $this -> authorize('edit', $group);
    if( !Auth::user() -> isGroupAdmin( $group -> id ) )
    {
      return back();
    }

    // Validate the input
    $messages = [
      'email.unique' => 'A user with that :attribute was already invited.',
    ];

    $email = $request->input('email');

    $rules = [
      'name' => 'max:255',
      'email' => [
        'required', 
        'email', 
        'max:255', 
        Rule::unique('group_invitations')->where(function ($query) use ($group, $email) {
          return $query->where('group_id', $group->id)
          ->where('email', $email);
        })
      ]
    ];

    Validator::make($request->all(), $rules, $messages) -> validate();

    // Send the invitation if the validation was successful
    $invitation = GroupInvitation::create([
      'inviter_user_id' => Auth::user() -> id,
      'group_id' => $group -> id,
      'name' => $request -> name,
      'email' => $request -> email,
    ]);

    $this -> sendInvitationMail( $invitation, $group -> name );

    return back();
  }

  // Sends a notification to the invited player
  // contains all the information needed to join the group
  protected function sendInvitationMail( $invitation, $groupName )
  {
    $inviterName = Auth::user()->name;

    Notification::route('mail', $invitation -> email)
      ->notify(new GroupInvitationMail( $invitation, $inviterName, $groupName ));
  }
}

resources/views/companion/group/group_characters.blade.php
@extends('layouts.companion_group')
@section('content')

  @if( sizeof( $characters ) > 0 )

    @include('companion.group_character.card_deck_characters')

  @else
    <div class="card">
      <div class="card-body">
        <em class="text-muted">@lang('character.no_character_yet')</em>
      </div>
    </div>
  @endif
@endsection

resources/views/companion/group/group_create.blade.php
@extends('layouts.companion_general')
@section('content')

  <h1 class="h3">@lang('group.create_new_group')</h1>

  <form method="POST" action="{{ route('group.store') }}" enctype="multipart/form-data">
    @csrf

    <p class="form-text">
      Um eine neue Gruppe zu erstellen, fülle einfach die unten angezeigten Felder aus. <br>
      Nachdem die Gruppe erfolgreich erstellt wurde kannst du das System wählen, Spieler hinzufügen und mehr Informationen angeben.
    </p>

    <div class="form-group">
      <label for="inputName">Name</label>
      <input type="text" name="name" class="form-control" value="{{ $group -> name or old('name') }}" id="inputName" placeholder="Name">
    </div>
    {{--
    <div class="form-group">
      <label for="inputName">@lang('group.game_system')</label>
      <select name="game_system_id" id="game_system_select" class="form-control" onChange="changedGameSystem(this, 'game-system-name')">
        @foreach($gameSystems as $gameSystem)
          <option value="{{$gameSystem -> id}}" {{old('game_system_id') == $gameSystem -> id ? "selected": ""}}>{{__($gameSystem -> name)}}</option>
        @endforeach
      </select>
      <small class="form-text text-muted"><i class="fas fa-exclamation"></i> Dieses System ermöglicht es dir einen eigenen Charakterbogen hochzuladen und diesen von deinen Spielern ausfüllen zu lassen.</small>
      <input type="text" name="game_system_name" class="form-control mt-2" value="{{ $group -> game_system_name or old('game_system_name') }}" id="inputGameSystem" placeholder="@lang('app.game_system.default_name')">
    </div>--}}
    <div class="form-group">
      <label for="inputDescription">Description</label>
      <textarea class="form-control" name="description" id="inputDescription" rows="3">{{ $group -> description or old('description') }}</textarea>
    </div>

    @include('shared.errors')

    <button type="submit" class="btn btn-primary float-left">{{ __('group.create') }}</button>
  </form>

  <script type="text/javascript">
    window.onload = function(){
      changedGameSystem(document.getElementById('game_system_select'), 'game-system-name');
    }
  </script>

@endsection

resources/views/companion/group/group_edit.blade.php
@extends('layouts.companion_group')
@section('content')

  @include('shared.errors')

  <div id="general" class="card mb-4">
    <div class="card-body">
      <!-- <h2 class="h5">@lang('group.menu_group_settings')</h2> -->
      <form method="POST" action="{{ route('group.update', [$group->id]) }}" enctype="multipart/form-data">
        @csrf
        @method('PUT')

        <div class="row">
          <div class="col-md-6">
            
            <div class="form-group">
              <label for="inputName" class="h5">@lang('group.name')</label>
              <input type="text" name="name" class="form-control" value="{{ old('name', $group -> name) }}" id="inputName" placeholder="Name">
            </div>

            <div class="form-group">
              <label for="inputDescription" class="h5">@lang('group.visibility')</label>
              <div class="form-check">
                <input class="form-check-input" type="radio" name="is_private" id="visibilityRadioPrivate" value="1" checked>
                <label class="form-check-label" for="visibilityRadioPrivate">
                  @lang('group.visibility_status.private')
                </label>
              </div>
              <div class="form-check">
                <input class="form-check-input" type="radio" name="is_private" id="visibilityRadioPublic" value="0" disabled>
                <label class="form-check-label" for="visibilityRadioPublic">
                  @lang('group.visibility_status.public')
                </label>
              </div>
            </div>

            <div class="form-group">
              <label for="inputNextSessionTime" class="h5">@lang('group.next_session')</label>
              <div class="row">
                <div class="form-group col-md-12">
                  <div class="input-group">
                    <div class="input-group-prepend">
                      <div class="input-group-text"><i class="far fa-clock"></i></div>
                    </div>
                    <input type="datetime-local" name="next_session_datetime" class="form-control" value="{{ isset( $group -> next_session_datetime ) ? old('next_session_datetime', $group -> next_session_datetime -> format('Y-m-d\TH:i')) : old('next_session_datetime') }}" id="inputNextSessionTime" placeholder="@lang('group.next_session_time')">
                  </div>
                </div>
                <div class="form-group col-md-12">
                  <div class="input-group">
                    <div class="input-group-prepend">
                      <div class="input-group-text"><i class="far fa-compass"></i></div>
                    </div>
                    <input type="text" name="next_session_location" class="form-control" value="{{ old('next_session_location', $group -> next_session_location) }}" id="inputNextSessionLocation" placeholder="@lang('group.next_session_location')">
                  </div>
                </div>
              </div>
            </div>
            
          </div>

          <div class="col-md-6">

            <div class="form-group">
              <label class="h5">@lang('group.image')</label>
              <!-- <div class="preview-image" style="background-image: url('{{ $group -> image }}');"></div> -->
              <img class="preview-image mb-2 d-block" id="groupImagePreview" src="{{ $group -> image }}">
              <div class="custom-file">
                <input type="file" class="custom-file-input" onChange="updatePreview(this, 'groupImagePreview')" id="validatedCustomFile" name="image">
                <label class="custom-file-label" for="validatedCustomFile">@lang('group.image_please_select')</label>
                <small class="form-text text-muted">@lang('group.image_help_text')</small>
              </div>
            </div>

          </div>

          <div class="col-md-12">
            <div class="form-group">
              <label for="inputDescription" class="h5">@lang('group.description')</label>
              <textarea class="form-control" name="description" id="inputDescription" rows="8">{{old('description', $group -> description)}}</textarea>
            </div>
          </div>

        </div>
        <!-- <div class="row mt-3">
          <div class="col-md-12">
            <label for="inputDescription">@lang('group.description')</label>
            <textarea class="form-control" name="description" id="inputDescription" rows="8">{{ $group -> description or old('description') }}</textarea>
          </div>
        </div> -->
        <button type="submit" class="btn btn-primary">@lang('group.save_changes')</button>
      </form>
    </div>
  </div>

  <div id="system" class="card">
    <div class="card-body">
      <h2 class="h5">@lang('group.game_system')</h2>
      <form method="POST" action="{{ route('group.game-system.update', [$group, $group->system]) }}" enctype="multipart/form-data">
        @csrf
        @method('PUT')
        <div class="form-group mb-0">
          <select name="game_system_id" id="game_system_select" class="form-control" onChange="changedGameSystem(this, 'game-system-wrapper')">
            @foreach($gameSystems as $gameSystem)
              <option value="{{$gameSystem -> id}}" {{old('game_system_id') == $gameSystem -> id ? "selected": ""}}>@lang($gameSystem -> name)</option>
            @endforeach
          </select>
        </div>
        <div id="game-system-wrapper">
          <small class="form-text text-muted mb-2"><i class="fas fa-exclamation"></i> @lang('app.game_system.default.helptext')</small>
          <div class="form-group">
            <label class="mb-0">@lang('group.game_system_name')</label>
            <input type="text" name="custom_name" class="form-control mt-2" value="{{ old('custom_game_system_name', $group -> system -> custom_name) }}" id="inputGameSystem" placeholder="@lang('app.game_system.default.name')">
          </div>
          <div class="form-group">
            <label class="mb-0">@lang('group.character_sheet')</label>
            <small class="form-text text-muted mt-0">@lang('app.game_system.default.character_sheet_helptext')</small>
            <div class="file d-flex align-items-center py-2">
              <div class="file-icon" style="font-size:2em">
                <i class="far fa-file"></i>
              </div>
              <div class="file-info px-2" style="flex: 1 0 0px;">
                @if(!empty($group -> system -> customFile))
                  <a class="file-title" href="{{route('files.download', [$group -> system -> customFile])}}" target="_blank"><i class="fas fa-download"></i> @lang('group.character_sheet')</a>
                  <div class="file-subtitle text-muted">
                    <small> 
                      @if(!empty($group -> system -> customFile->size))
                        {{$group -> system -> customFile -> size}},  
                      @endif
                      @lang('app.file.modified_at', ['time' => $group -> system -> customFile -> created_at -> diffForHumans()])
                    </small>
                  </div>
                @else
                  <span class="text-muted font-italic" id="no-file-uploaded-message">@lang('app.character_sheet_not_uploaded')</span>
                @endif
              </div>
              <div class="file-buttons d-flex">
                <div class="upload-btn-wrapper ml-2">
                  <button class="btn btn-primary btn-sm"><i class="fas fa-upload"></i> @lang('app.upload')</button>
                  <input type="file" name="custom_file" id="input-character-sheet" />
                </div>
              </div>
            </div>
          </div>
        </div>

        <button type="submit" class="btn btn-primary">@lang('group.save_changes')</button>
      </form>
    </div>
  </div>

  <div class="card mt-4">
    <div class="card-body">
      <h2 class="h5">@lang('group.delete_group')</h2>
        <p>@lang('group.delete_group_text')</p>
        <button type="submit" data-toggle="modal" data-target="#group-destroy" class="btn btn-danger">@lang('group.delete')</button>
    </div>
  </div>
  @component('shared.modal.modal_confirmation', ['id' => 'group-destroy', 'url' => route('group.destroy', [$group]), 'method' => 'DELETE'])
    @lang('group.delete_confirmation', ['name' => $group -> name])
  @endcomponent

  <script type="text/javascript">
    document.getElementById('input-character-sheet').onchange = function () {
      var message = document.getElementById('no-file-uploaded-message');
      message.innerHTML = this.value.replace(/.*[\/\\]/, '');
      message.classList.remove('text-muted');
      message.classList.remove('font-italic')
    };
  </script>
@endsection

resources/views/companion/group/group_files.blade.php
@extends('layouts.companion_group')
@section('content')
  All files
  @foreach($group->files as $file)
  	{{ $file -> name }}
  @endforeach
@endsection

resources/views/companion/group/group_pending_invite.blade.php
@extends('layouts.companion')
@section('content')
  <div class="card">
    <div class="card-body">
      <h2 class="h4">{{$group->name}}</h2>
      <p>{!! __('app.notifications.pending_invite_this_group', ['name' => htmlspecialchars($pendingInvitation -> inviter -> name)]) !!}</p>
      <div class="text-center">
        <a class="btn btn-outline-success btn-sm" href="{{route('group.invitation.accept', [$group, $pendingInvitation])}}">@lang('app.accept')</a>
        <a class="btn btn-outline-danger btn-sm" href="{{route('group.invitation.reject', [$group, $pendingInvitation])}}">@lang('app.decline')</a>
      </div>
    </div>
  </div>
@endsection

resources/views/companion/group/group_private.blade.php
@extends('layouts.companion')
@section('body')

  @if( !empty( $pendingInvitation ) )
    <div class="container mt-5">
      <div class="row justify-content-md-center">

        <div class="col-md-6">
          <div class="card">
            <div class="card-body">
              <h2 class="h4">{{$group->name}}</h2>
              <p>{!! __('app.notifications.pending_invite_this_group', ['name' => htmlspecialchars($pendingInvitation -> inviter -> name)]) !!}</p>
              <div class="text-center">
                <a class="btn btn-outline-success btn-sm" href="{{route('group.invitation.accept', [$group, $pendingInvitation])}}">@lang('app.accept')</a>
                <a class="btn btn-outline-danger btn-sm" href="{{route('group.invitation.reject', [$group, $pendingInvitation])}}">@lang('app.decline')</a>
              </div>
            </div>
          </div>
          
        </div>
      </div>
    </div>
  @else
    <div class="container mt-5">
      <div class="row justify-content-md-center">

        <div class="col-md-6">
          <div class="card">
            <div class="card-body text-center">
              <h2><i class="fas fa-ban text-muted"></i></h2>
              <p>@lang('group.private_group.message')</p>
              <a href="{{route('home')}}" class="btn btn-outline-primary btn-sm"><i class="fas fa-home"></i> @lang('group.private_group.back_to_my_groups')</a>
            </div>
          </div>
          
        </div>
      </div>
    </div>
  @endif

@endsection

resources/views/companion/group/group_user.blade.php
@extends('layouts.companion_group')
@section('content')

  <div class="card">
    <div class="card-body">
      <h3>{{ $user -> name }}</h3>
      @if( $user->joined_group_at != null )
        <strong>Gruppe beigetreten:</strong> {{$user->joined_group_at->toFormattedDateString()}} ({{$user->joined_group_at->diffForHumans()}})
      @endif
    </div>
  </div>
  
@endsection