routes/web.php
<?php

// determine the language
$lang = Request::server('HTTP_ACCEPT_LANGUAGE');
if( isset( explode(',', $lang)[0] ) )
{
	App::setLocale( explode(',', $lang)[0] );
}

App::setLocale('de');

Auth::routes();

// Player
// the player does not have to be authorized to access the character sheet and group
Route::group(['middleware' => ['playerAccess']], function() {
	// TODO: were player specific views -> now user specific
	// Route::resource('group/{group}/player/{player}/file', 'Companion\PlayerFileController');
	// Route::resource('group/{group}/player/{player}/character', 'Companion\CharacterController');
	// Route::post('group/{group}/player/{player}/character/{characterId}/set-active', 'Companion\CharacterController@setActive') -> name('character.make_active');
});

// HomeController determines which view should be rendered
Route::get('/', 'HomeController@index') -> name('home');


// all frontend routes
Route::group( [], function(){
  Route::get('register', function(){ 
    return view('public.register'); 
  }) -> name('register');
	Route::get('privacy-policy', function(){
		return view('public.privacy_policy');
	}) -> name('privacy-policy');
	Route::get('imprint', function(){
		return view('public.imprint');
	}) -> name('imprint');
	Route::get('features', 'HomeController@showFeatures');
});


// all backend routes for the companion app are protected
Route::group(['middleware' => ['auth']], function () {

	// Logout
	Route::get('logout', function(){
		Auth::logout();
		return redirect('/');
	}) -> name('logout');

  Route::resource('user', 'Companion\UserProfileController');
  Route::post('user/{user}/changePassword', 'Companion\UserProfileController@changePassword') -> name('user.change_password');
	

  Route::get('files/{file}/download', 'Companion\FileController@download') -> name('files.download');
  Route::delete('files/{file}', 'Companion\FileController@destroy') -> name('files.destroy');
	
  // Group
  Route::resource('group', 'Companion\GroupController');

  // Group.* routes
  Route::name('group.')->middleware('can:view,group')->group( function(){

    // Group
		Route::post('group/{group}/invite-user', 'Companion\GroupController@inviteUser') -> name('invite_user');
		Route::post('group/{group}/remove-player', 'Companion\GroupController@removePlayer') -> name('remove_player');

    Route::resource('group/{group}/game-system', 'Companion\GroupGameSystemController') -> only(['update']);

    // TODO!!!
    // accept and reject need to be POST methods!
    Route::name('invitation.')->group( function() {
      Route::get('group/{group}/invitation/{groupInvitation}/accept', 'Companion\GroupInvitationController@accept')->name('accept');
  		Route::get('group/{group}/invitation/{groupInvitation}/reject', 'Companion\GroupInvitationController@reject')->name('reject');
      Route::delete('group/{group}/invitation/{groupInvitation}/destroy', 'Companion\GroupInvitationController@destroy')->name('destroy');
    });

    // Group Users
    // Route::resource('group/{group}/character', 'Companion\GroupCharacterController');
    Route::resource('group/{group}/user', 'Companion\GroupUserController') -> only(['show', 'index', 'destroy']);

    Route::get('group/{group}/characters', 'Companion\GroupController@showCharacters') -> name('characters');

    Route::get('group/{group}/user/{user}/character', 'Companion\GroupCharacterController@show') -> name('character');
    Route::put('group/{group}/user/{user}/character', 'Companion\GroupCharacterController@update') -> name('character.update');

    // Characters
    Route::name('character.')->group( function() {

      // Characters
      Route::resource('group/{group}/character/{character}/file', 'Companion\GroupCharacterFileController') -> only(['store', 'show', 'destroy']);
      Route::name('file.')->group( function() {
        // Character Files
        Route::get('group/{group}/character/{character}/file/{file}/download', 'Companion\GroupCharacterFileController@download') -> name('download');
      });

    });

  });
	

	// User Settings
	// Route::resource('user', 'Companion\UserProfileController');

});

app/Http/Controllers/Companion/FileController.php
<?php

namespace App\Http\Controllers\Companion;

use App\File;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;

class FileController extends Controller
{
  public function download(Request $request, File $file)
  {
    return Storage::disk('public')->download($file->path);
  }

  public function show(Request $request, File $file)
  {
    return response() -> file( Storage::disk('public')->path($file->path) );
  }

  public function destroy(Request $request, File $file)
  {
    $file -> delete();
    return back();
  }
}

app/Http/Controllers/Companion/GroupCharacterController.php
<?php

namespace App\Http\Controllers\Companion;

use Illuminate\Http\Request;
use App\Group;
use App\User;
use App\Character;
use App\Http\Controllers\Controller;

class GroupCharacterController extends Controller
{

  public function show(Request $request, Group $group, User $user)
  {
    $character = Character::firstOrNew(['user_id' => $user->id, 'group_id' => $group->id]);

    $this -> authorize('view', $group);
    if( !empty( $character -> additional_data ) )
    {
      $character -> additional_data = json_decode($character -> additional_data, true);
    }

    $files = $character -> files;
    $characterSheet = null;

    $files = $files -> filter(function ($value, $key) use ($characterSheet) {
      if( $value -> file_type == config('tablegamers.file_types.character_sheet') )
      {
        $characterSheet = $value;
        return false;
      }
    });

    if( auth() -> id() == $user -> id )
    {
      return view('companion.group_character.character_edit') -> with(compact('group', 'character', 'files'));
    }
    return view('companion.group_character.character') -> with(compact('group', 'character', 'files', 'characterSheet'));
  }

  public function update(Request $request, Group $group)
  {
    $request -> validate([
      'name' => 'required|max:255',
      'image' => 'image|max:5000',
      'gender' => 'max:255',
      'age' => 'nullable|integer',
      'race' => 'max:255',
      'classname' => 'max:255',
    ]);

    $character = Character::firstOrCreate(['user_id' => auth()->user()->id, 'group_id' => $group -> id]);
    $character -> fill( $request -> all() );

    // collect additional data from request
    $requestData = $request -> all();
    unset($requestData['_token']);
    unset($requestData['_method']);
    $requestDataJson = json_encode($requestData);
    $character -> additional_data = $requestDataJson;

    if( $request -> has('image') ){
      $path = $request -> image -> store('character_images', 'public');
      $character -> image = $path;
    }

    $character -> save();
    return back();
  }
}

app/Http/Controllers/Companion/GroupCharacterFileController.php
<?php

namespace App\Http\Controllers\Companion;

use App\Character;
use App\CharacterFile;
use App\Group;
use App\File;
use App\Http\Controllers\Controller;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Illuminate\Validation\Rule;

class GroupCharacterFileController extends Controller
{
    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request, Group $group, Character $character)
    {
      $request -> validate([
        'file' => 'required|file|max:5000',
        'name' => 'required|max:255',
        'file_type' => [
          'required',
          Rule::in(config('tablegamers.file_types')),
        ]
      ]);

      // store the file
      if( $request -> has('file') )
      {
        $path = $request -> file -> store('character_files', 'public');
        $file = new File();
        $file -> uploader_user_id = $character -> user -> id;
        $file -> name = $request -> name;
        $file -> mime_type = $request -> file -> getMimeType();
        $file -> path = $path;

        $character -> files() -> save($file, ['file_type' => $request -> file_type]);

        return back() -> with(['success' => 'File uploaded successful']);
      }
      return back() -> with(['error' => 'Nope!']);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Request $request, Group $group, Character $character, CharacterFile $file)
    {
      $characterFile = Storage::disk('public')->path($file -> filename);
      return response()->file($characterFile);
    }

    /**
     *  Download a specific character file
     *
     */
    public function download(Request $request, Group $group, Character $character, CharacterFile $file)
    {
      return Storage::disk('public')->download($file -> filename);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request, Group $group, Character $character, CharacterFile $file)
    {
      $file -> delete();
      return back();
    }
}

app/Http/Controllers/Companion/GroupController.php
<?php

namespace App\Http\Controllers\Companion;

use App\Character;
use App\GameSystem;
use App\Group;
use App\GroupGameSystem;
use App\GroupInvitation;
use App\Http\Controllers\Controller;
use App\Models\Misc\GroupProgress;
use App\Notifications\GroupInvitationMail;
use App\Player;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Gate;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Facades\Notification;
use Illuminate\Support\Facades\Storage;
use Illuminate\Validation\Rule;
use Validator;

class GroupController extends Controller
{

  /**
   * Show the form for creating a new resource.
   *
   * @return \Illuminate\Http\Response
   */
  public function create()
  {
    $gameSystems = GameSystem::get();
    return view('companion.group.group_create') -> with(compact('gameSystems'));
  }

  /**
   * Store a newly created resource in storage.
   *
   * @param  \Illuminate\Http\Request  $request
   * @return \Illuminate\Http\Response
   */
  public function store(Request $request)
  {
    $request->validate([
      'name' => 'required|max:255'
    ]);

    $group = new Group;
    $group -> name = $request -> name;
    $group -> save();

    GroupGameSystem::create(['group_id' => $group -> id, 'is_custom_system' => true, 'game_system_id' => config('tablegamers.game_system_default_id')]);

    // intermediate table
    Auth::user()->groups()->attach($group, ['is_admin' => true]);

    return redirect() -> route('home');
  }

  /**
   * Display the specified resource.
   *
   * @param  int  $id
   * @return \Illuminate\Http\Response
   */
  public function show(Group $group, $playerIdentifier = null)
  {
    $this -> authorize('view', $group);
    // if( Gate::denies('view', $group) )
    // {
    //   // Show the "this group is private message"
    //   return view('companion.group.group_private') -> with(compact(['group']));
    // }

    $group -> load(['users', 'characters', 'system']);
    $isGroupAdmin = Auth::user()->isGroupAdmin( $group -> id );

    // calculate group progress
    $progress = new GroupProgress();
    $progress -> calculate($group, auth()->user(), auth()->user()->can('edit', $group));

    return view('companion.group.group')->with(compact(['group', 'isGroupAdmin', 'progress']));
  }

  /**
   * Show the form for editing the specified resource.
   *
   * @param  int  $id
   * @return \Illuminate\Http\Response
   */
  public function edit(Group $group)
  {
    $this -> authorize('edit', $group);
    $gameSystems = GameSystem::get();

    return view('companion.group.group_edit')->with(compact('group', 'gameSystems'));
  }

  /**
   * Update the specified resource in storage.
   *
   * @param  \Illuminate\Http\Request  $request
   * @param  int  $id
   * @return \Illuminate\Http\Response
   */
  public function update(Request $request, Group $group)
  {
    $this -> authorize('edit', $group);
    $request->validate([
      'name' => 'required|max:255',
      'image' => 'image|max:5000',
      // 'next_session_datetime' => 'date',
      'next_session_location' => 'max:255',
      'is_private' => 'boolean',
    ]);

    // find the group and update the values
    $group -> name = $request -> name;
    $group -> description = $request -> description;

    $group -> next_session_datetime = $request -> next_session_datetime;
    $group -> next_session_location = $request -> next_session_location;

    // TODO: If public groups are supported, this needs to be adjusted!
    $group -> is_private = true;

    // store the image
    if( $request -> has('image') ){
      $path = $request -> image -> store(config('tablegamers.group_images_folder'), 'public');
      $group -> image = $path;
    }

    $group -> save();

    return redirect()->route('group.show', [$group->id]);
  }

  /**
   * Remove the specified resource from storage.
   *
   * @param  int  $id
   * @return \Illuminate\Http\Response
   */
  public function destroy(Group $group)
  {
    $this -> authorize('edit', $group);

    $group -> delete();

    return redirect() -> route('home');
  }

  public function showCharacters(Request $request, Group $group)
  {
    $this -> authorize('view', $group);

    $usersWithoutCharacter = $group -> users() -> whereDoesntHave('characters', function($query) use ($group){
      $query -> where('group_id', $group->id);
    }) -> get();

    // sort users so that the current authenticated user is first
    $usersWithoutCharacter = $usersWithoutCharacter -> sortBy(function ($user, $key) {
      if( $user -> id == auth()->id() )
        return -1;
      else
        return $user['name'];
      });

    $characters = $group -> characters;

    return view('companion.group.group_characters')->with(compact('group', 'characters', 'usersWithoutCharacter'));
  }

  public function inviteUser(Request $request, Group $group)
  {
    $this -> authorize('edit', $group);
    if( !Auth::user() -> isGroupAdmin( $group -> id ) )
    {
      return back();
    }

    // Validate the input
    $messages = [
      'email.unique' => 'A user with that :attribute was already invited.',
    ];

    $email = $request->input('email');

    $rules = [
      'name' => 'max:255',
      'email' => [
        'required', 
        'email', 
        'max:255', 
        Rule::unique('group_invitations')->where(function ($query) use ($group, $email) {
          return $query->where('group_id', $group->id)
          ->where('email', $email);
        })
      ]
    ];

    Validator::make($request->all(), $rules, $messages) -> validate();

    // Send the invitation if the validation was successful
    $invitation = GroupInvitation::create([
      'inviter_user_id' => Auth::user() -> id,
      'group_id' => $group -> id,
      'name' => $request -> name,
      'email' => $request -> email,
    ]);

    $this -> sendInvitationMail( $invitation, $group -> name );

    return back();
  }

  // Sends a notification to the invited player
  // contains all the information needed to join the group
  protected function sendInvitationMail( $invitation, $groupName )
  {
    $inviterName = Auth::user()->name;

    Notification::route('mail', $invitation -> email)
      ->notify(new GroupInvitationMail( $invitation, $inviterName, $groupName ));
  }
}

app/Http/Controllers/Companion/GroupGameSystemController.php
<?php

namespace App\Http\Controllers\Companion;

use App\File;
use App\Group;
use App\GroupGameSystem;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class GroupGameSystemController extends Controller
{
  /**
   * Update the specified resource in storage.
   *
   * @param  \Illuminate\Http\Request  $request
   * @param  int  $id
   * @return \Illuminate\Http\Response
   */
  public function update(Request $request, Group $group, GroupGameSystem $game_system)
  {
    $this -> authorize('update', [$game_system, $group]);

    $request->validate([
      'custom_name' => 'required|max:255',
      'game_system_id' => 'required|exists:game_systems,id',
    ]);

    if( $request -> game_system_id == config('tablegamers.game_system_default_id') )
    {
      $game_system -> custom_name = $request -> custom_name;
      $game_system -> game_system_id = $request -> game_system_id;

      if( $request -> has('custom_file') )
      {
        $path = $request -> custom_file -> store(config('tablegamers.group_character_sheet_folder'), 'public');

        $file = new File();
        $file -> uploader_user_id = auth()->id();
        $file -> mime_type = $request -> custom_file -> getMimeType();
        $file -> name = config('tablegamers.game_system_default_file_name');
        $file -> path = $path;
        $file -> save();

        $game_system -> custom_file_id = $file -> id;
      }

      $game_system -> save();
    }

    return back();
  }
}

resources/views/companion/group_character/card_deck_characters.blade.php
<div class="row">
  @foreach($characters as $character)
    <div class="col-md-3">
      <div class="card text-center mb-4">
        @if( isset( $currentCharacter ) && $currentCharacter -> id == $character -> id )
          <div class="card-body border border-primary rounded">
        @else
          <div class="card-body">
        @endif
          <a href="{{route('group.character', [$group, $character->user])}}">
            <div class="position-relative avatar-u-lg mx-auto mb-3">
              <img class="img-fluid rounded-circle border" src="{{ $character -> image }}" alt="Image Description">
            </div>
          </a>
          <h2 class="h6 mb-0">
            <a href="{{route('group.character', [$group, $character->user])}}">{{ $character -> name }}</a>
          </h2>
          <a class="small" href="{{route('group.user.show', [$group, $character->user])}}">{{ $character -> user -> name }}</a>
        </div>
      </div>
    </div>
  @endforeach
</div>

resources/views/companion/group_character/card_deck_characters_edit.blade.php
<div class="row">
  @foreach($characters as $character)
    <div class="col-md-3">
      <div class="card text-center mb-4">
        @if( isset( $currentCharacter ) && $currentCharacter -> id == $character -> id )
          <div class="card-body border border-primary rounded">
        @else
          <div class="card-body">
        @endif
          <a href="{{route('group.character.show', [$group, $character])}}">
            <div class="position-relative avatar-u-lg mx-auto mb-3">
              <img class="img-fluid rounded-circle border" src="{{ $character -> image }}" alt="Image Description">
              <span class="badge"><i class="fas fa-star"></i></span>
            </div>
          </a>
          <h2 class="h6 mb-0">
            <a href="{{route('group.character.show', [$group, $character])}}">{{ $character -> name }}</a>
          </h2>
        </div>
        <div class="card-footer">
          <a href="{{route('group.character.edit', [$group, $character])}}" class="btn btn-outline-info btn-sm mr-2"><i class="fas fa-pencil-alt"></i> edit</a>
          <button data-toggle="modal" data-target="#character-destroy-{{$character->id}}" class="btn btn-outline-danger btn-sm"><i class="fas fa-times"></i> delete</button>
        </div>
      </div>
    </div>
    @can('delete', [$character])
      @component('shared.modal.modal_confirmation', ['id' => 'character-destroy-'.$character->id, 'url' => route('group.character.destroy', [$group, $character]), 'method' => 'DELETE'])
        @lang('character.delete_confirmation', ['name' => $character -> name])
      @endcomponent
    @endcan
  @endforeach
</div>

resources/views/companion/group_character/character.blade.php
@extends('layouts.companion_group')
@section('content')

<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{{route('group.characters', [$group])}}">@lang('group.characters')</a></li>
    <li class="breadcrumb-item active">{{ $character -> name }}</li>
  </ol>
</nav>

<div class="row">
  <div class="col-md-6">
    <div class="card mb-4">
      <div class="card-body">
        <div class="character-info">
          <h2 class="h5">@lang('character.character_sheet')</h2>
          
          @if($character -> characterSheetFiles -> isEmpty())
            <small class="text-muted">@lang('character.character_sheet_none_uploaded')</small>
          @else
            @foreach($character->characterSheetFiles as $file)
              @include('shared.file')
            @endforeach
          @endif
        </div>
      </div>
    </div>
  </div>
  <div class="col-md-6">
    <div class="card mb-4">
      <div class="card-body character-info">
        <div class="row">
          <div class="col-md-6 d-flex align-items-center">
            <div class="character-avatar mr-4">
              <img src="{{$character->image}}">
            </div>
            <div class="character-attribute">
              <label>@lang('character.name')</label>
              <div>{{ $character -> name }}</div>
            </div>
          </div>
          <div class="col-md-6">
            <div class="character-attribute">
              <label>@lang('character.user_name')</label>
              <small><a href="{{route('group.user.show', [$group, $character -> user])}}">{{ $character -> user -> name }}</a></small>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-md-12">
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="col-md-12">
    <div class="card">
      <div class="card-body character-info">
        <div class="character-attribute">
          <label>@lang('character.description_short')</label>
          @if(!empty($character -> description))
            <div>{{ $character -> description }}</div>
          @else
            <div>@lang('character.description_none_set')</div>
          @endif
        </div>
      </div>
    </div>
  </div>
</div>
@endsection

resources/views/companion/group_character/character_create.blade.php
@extends('layouts.companion_group')

@section('content')
  <div class="card">
    <div class="card-body">
      <h3>{{ __('character.create_character') }}</h3>
      @include('shared.errors')
      <form action="{{ route('group.character.store', [$group]) }}" method="POST" enctype="multipart/form-data">
        @csrf

        <div class="row">
          <div class="col-md-7">
            <div class="form-group">
              <label>@lang('character.name')</label>
              <input type="text" class="form-control" name="name" value="{{ old('name') }}" placeholder="@lang('character.name')">
            </div>
            
            <div class="form-row">
              <div class="form-group col-md-12">
                <label>@lang('character.gender')</label>
                <input type="text" class="form-control" name="gender" value="{{ old('gender') }}" placeholder="@lang('character.gender')">
              </div>
              <div class="form-group col-md-12">
                <label>@lang('character.age')</label>
                <input type="text" class="form-control" name="age" value="{{ old('age') }}" placeholder="@lang('character.age')">
              </div>
            </div>

            <!--
            <div class="form-group">
              <label>@lang('character.class')</label>
              <input type="text" class="form-control" name="classname" value="{{ old('classname') }}" placeholder="@lang('character.class')">
            </div>
            <div class="form-group">
              <label>@lang('character.race')</label>
              <input type="text" class="form-control" name="race" value="{{ old('race') }}" placeholder="@lang('character.race')">
            </div>
            -->

          </div>
          <div class="col-md-5">
            <div class="mb-3">
              <!-- <label>@lang('character.image')</label> -->
              <div class="preview-image" id="characterImagePreview" style="background-image: url('/img/character_placeholder.jpg'); min-height: 14em"></div>
              <div class="custom-file mt-2">
                <input type="file" class="custom-file-input" onChange="updatePreviewBackground(this, 'characterImagePreview')" id="validatedCustomFile" name="image">
                <label class="custom-file-label" for="validatedCustomFile">@lang('group.image_please_select')</label>
                <div class="invalid-feedback">Example invalid custom file feedback</div>
                <small class="form-text text-muted">@lang('group.image_help_text')</small>
              </div>
            </div>
          </div>
        </div>

        <!--
        <div class="row">
          <div class="col-md-12">
            <div class="form-group">
              <label>@lang('character.description')</label>
              <textarea class="form-control" name="description" rows="10" placeholder="@lang('character.description')">{{ old('description') }}</textarea>
            </div>
          </div>
        </div>
        -->

        <button type="submit" class="btn btn-primary">{{ __('character.create') }}</button>
      </form>
    </div>
  </div>
  
@endsection

resources/views/companion/group_character/character_edit.blade.php
@extends('layouts.companion_group')
@section('content')
  <div class="card mb-4">
    <div class="card-body">
      <div class="row">

        <div class="col-md-6 mb-4">
          <h2 class="h5">@lang('character.your_character_sheet')</h2>
          <!-- <h3 class="h6 subtitle text-muted">Informationen zu deinem Charakter</h3> -->

          @if(!$character -> characterSheetFiles -> isEmpty())
            @foreach($character -> characterSheetFiles as $file)
              @include('shared.file_default', ['file' => $file, 
              'defaultName' => __('character.character_sheet'),
              'fileDownloadLink' => route('files.download', [$file]), 
              'fileDeleteLink' => route('files.destroy', [$file])
              ])
            @endforeach
          @else
            <div class="alert alert-warning">Du hast noch keinen Charakterbogen hochgeladen.</div>
          @endif
          <form action="{{ route('group.character.file.store', [$group, $character]) }}" method="POST" enctype="multipart/form-data" id="character-sheet-form">
            @csrf
            <input type="hidden" name="file_type" value="character_sheet">
            
            <h6>Datei hinzufügen</h6>
            <div class="form-group">
              <input type="text" class="form-control form-control-sm" name="name" value="{{ old('sheet-file-name') }}" placeholder="@lang('character.name')">
            </div>
            <div class="form-group">
              <input type="file" name="file">
            </div>

            <button class="btn btn-primary">Hochladen</button>
            
          </form>

          @include('shared.errors')
        </div>
        <div class="col-md-6 mb-4">
          <i class="far fa-question-circle"></i>

          <p><small>@lang('character.your_character_sheet_help_text')</small></p>

          Vorlage:<br>
          @if($group -> system -> customFile)
            <p>@lang('group.character_sheet_text_1')</p>
            <a href="{{route('files.download', [$group -> system -> customFile])}}"><i class="fas fa-download"></i> @lang('group.character_sheet')</a>
          @else
            <p><small><em>@lang('character.character_sheet_text_1_no_sheet')</em></small></p>
          @endif
        </div>
          


      </div>
    </div>
  </div>

  <div class="card mb-4">
    <div class="card-body">
      <h2 class="h5">Charakterinformationen für deine Gruppe</h2>
      <!-- <h3 class="subtitle h6 mb-3 text-muted">Informationen für deine Gruppe</h3> -->
      
      <form action="{{ route('group.character.update', [$group, $character]) }}" method="POST" enctype="multipart/form-data">
        @csrf
        @method('PUT')

        <div class="form-group">
          <div class="media">
            <div class="fileinput-button character-avatar">
              <img src="{{$character->image}}" id="characterImagePreview" class="preview-image">
              <input type="file" class="custom-file-input" onChange="updatePreviewImage(this, 'characterImagePreview')" id="validatedCustomFile" name="image">
            </div>
            <div class="media-body pl-3">
              <h3 class="media-title">Dein Charakterbild</h3>
              <h6 class="media-subtitle text-muted">Klicke auf den Avatar um das Bild zu ändern.</h6>
            </div>
          </div>
        </div>

        <div class="form-group">
          <label>@lang('character.name')</label>
          <input type="text" class="form-control" name="name" value="{{ $character -> name or old('name') }}" placeholder="@lang('character.name')">
        </div>

          <div class="form-group">
            <!--
            <div class="custom-file my-2">
              <input type="file" class="custom-file-input" onChange="updatePreviewImage(this, 'characterImagePreview')" id="validatedCustomFile" name="image">
              <label class="custom-file-label" for="validatedCustomFile">@lang('group.image_please_select')</label>
              <div class="invalid-feedback">Example invalid custom file feedback</div>
              <small class="form-text text-muted">@lang('group.image_help_text')</small>
            </div>
            -->
          </div>

          <div class="form-group">
            <label>@lang('character.description_short')</label>
            <textarea class="form-control" name="description" rows="10" placeholder="@lang('character.description_short')">{{ $character -> description or old('description') }}</textarea>
          </div>

        @include('shared.errors')

        <button type="submit" class="btn btn-primary">{{ __('character.save_changes') }}</button>
      </form>
    </div>
  </div>
@endsection

resources/views/companion/group_character/character_empty.blade.php
@extends('layouts.companion_group')
@section('content')

  <div class="card">
    <div class="card-body">

      <h2 class="h5">
        @if( Auth::id() == $user->id )
          @lang('group.menu_my_characters')
        @else
          {{$user->name}}
        @endif
      </h2>

      <em class="text-muted">{!! __('character.no_character_yet_text') !!}</em>
      <a class="btn btn-outline-info mt-2" href="{{route('group.character.create', [$group])}}">
        <i class="fas fa-user-plus"></i> @lang('character.create')
      </a>
    </div>
  </div>
  
@endsection