routes/web.php
<?php

// determine the language
$lang = Request::server('HTTP_ACCEPT_LANGUAGE');
if( isset( explode(',', $lang)[0] ) )
{
	App::setLocale( explode(',', $lang)[0] );
}

App::setLocale('de');

Auth::routes();

// Player
// the player does not have to be authorized to access the character sheet and group
Route::group(['middleware' => ['playerAccess']], function() {
	// TODO: were player specific views -> now user specific
	// Route::resource('group/{group}/player/{player}/file', 'Companion\PlayerFileController');
	// Route::resource('group/{group}/player/{player}/character', 'Companion\CharacterController');
	// Route::post('group/{group}/player/{player}/character/{characterId}/set-active', 'Companion\CharacterController@setActive') -> name('character.make_active');
});

// HomeController determines which view should be rendered
Route::get('/', 'HomeController@index') -> name('home');


// all frontend routes
Route::group( [], function(){
  Route::get('register', function(){ 
    return view('public.register'); 
  }) -> name('register');
	Route::get('privacy-policy', function(){
		return view('public.privacy_policy');
	}) -> name('privacy-policy');
	Route::get('imprint', function(){
		return view('public.imprint');
	}) -> name('imprint');
	Route::get('features', 'HomeController@showFeatures');
});


// all backend routes for the companion app are protected
Route::group(['middleware' => ['auth']], function () {

	// Logout
	Route::get('logout', function(){
		Auth::logout();
		return redirect('/');
	}) -> name('logout');

  Route::resource('user', 'Companion\UserProfileController');
  Route::post('user/{user}/changePassword', 'Companion\UserProfileController@changePassword') -> name('user.change_password');
	

  Route::get('files/{file}/download', 'Companion\FileController@download') -> name('files.download');
  Route::delete('files/{file}', 'Companion\FileController@destroy') -> name('files.destroy');
	
  // Group
  Route::resource('group', 'Companion\GroupController');

  // Group.* routes
  Route::name('group.')->middleware('can:view,group')->group( function(){

    // Group
		Route::post('group/{group}/invite-user', 'Companion\GroupController@inviteUser') -> name('invite_user');
		Route::post('group/{group}/remove-player', 'Companion\GroupController@removePlayer') -> name('remove_player');

    Route::resource('group/{group}/game-system', 'Companion\GroupGameSystemController') -> only(['update']);

    // TODO!!!
    // accept and reject need to be POST methods!
    Route::name('invitation.')->group( function() {
      Route::get('group/{group}/invitation/{groupInvitation}/accept', 'Companion\GroupInvitationController@accept')->name('accept');
  		Route::get('group/{group}/invitation/{groupInvitation}/reject', 'Companion\GroupInvitationController@reject')->name('reject');
      Route::delete('group/{group}/invitation/{groupInvitation}/destroy', 'Companion\GroupInvitationController@destroy')->name('destroy');
    });

    // Group Users
    // Route::resource('group/{group}/character', 'Companion\GroupCharacterController');
    Route::resource('group/{group}/user', 'Companion\GroupUserController') -> only(['show', 'index', 'destroy']);

    Route::get('group/{group}/characters', 'Companion\GroupController@showCharacters') -> name('characters');

    Route::get('group/{group}/user/{user}/character', 'Companion\GroupCharacterController@show') -> name('character');
    Route::put('group/{group}/user/{user}/character', 'Companion\GroupCharacterController@update') -> name('character.update');

    // Characters
    Route::name('character.')->group( function() {

      // Characters
      Route::resource('group/{group}/character/{character}/file', 'Companion\GroupCharacterFileController') -> only(['store', 'show', 'destroy']);
      Route::name('file.')->group( function() {
        // Character Files
        Route::get('group/{group}/character/{character}/file/{file}/download', 'Companion\GroupCharacterFileController@download') -> name('download');
      });

    });

  });
	

	// User Settings
	// Route::resource('user', 'Companion\UserProfileController');

});

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}" class="has-navbar-fixed-top">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- CSRF Token -->
  <meta name="csrf-token" content="{{ csrf_token() }}">

  <title>{{ __('app.app_title') }}@yield('titleAddition')</title>

  <link rel="shortcut icon"  href="/favicon.ico?ver=2.0" type="image/x-icon"/>
  <link href="https://fonts.googleapis.com/css?family=Roboto+Slab:400,700" rel="stylesheet">

  <!-- Styles -->
  @yield('head')
</head>
<body>
  @yield('main')
</body>
</html>

resources/views/layouts/companion.blade.php
@extends('layouts.app')
@section('head')
  <link href="{{ asset('css/companion.css') }}" rel="stylesheet">
@endsection
@section('main')
  <nav class="navbar navbar-light navbar-expand-lg">
    <div class="container">

      <div>
        <a class="navbar-brand brand-font mr-4" href="{{route('home')}}">table<span class="text-dark">gamers</span></a>
      </div>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link {{ request()->routeIs('home') ? 'active' : '' }}" href="{{route('home')}}">@lang('app.main_nav.dashboard')</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="my-groups-dropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              @lang('app.main_nav.my_groups')
            </a>

            <div class="dropdown-menu" aria-labelledby="my-groups-dropdown">

              @if( $mainNavGroupsAsAdmin -> isEmpty() && $mainNavGroupsAsPlayer -> isEmpty() )
                <h6 class="dropdown-header">@lang('app.main_nav.no_groups_yet')</h6>
              @else

                @if( $mainNavGroupsAsAdmin -> isNotEmpty() )
                  <h6 class="dropdown-header">@lang('app.main_nav.groups_as_admin')</h6>
                  @foreach( $mainNavGroupsAsAdmin as $group )
                    <a class="dropdown-item" href="{{route('group.show', [$group])}}">{{$group -> name}}</a>
                  @endforeach
                @endif

                @if( $mainNavGroupsAsAdmin -> isNotEmpty() && $mainNavGroupsAsPlayer -> isNotEmpty() )
                  <div class="dropdown-divider"></div>
                @endif

                @if( $mainNavGroupsAsPlayer -> isNotEmpty() )
                  <h6 class="dropdown-header">@lang('app.main_nav.groups_as_player')</h6>
                  @foreach( $mainNavGroupsAsPlayer as $group )
                    <a class="dropdown-item" href="{{route('group.show', [$group])}}">{{$group -> name}}</a>
                  @endforeach
                @endif
              @endif
            </div>
          </li>
        </ul>
        <ul class="navbar-nav ml-auto">
          <li class="nav-item dropdown pr-3">
            <a href="" class="nav-link dropdown-toggle notification" data-toggle="dropdown" href="#" id="alertsDropdown" role="button" aria-expanded="false">
              <i class="align-middle far fa-bell"></i>
              @if( count( Auth::user() -> invitations) > 0 )
                <span class="badge">{{ count( Auth::user() -> invitations ) }}</span>
              @endif
            </a>

            <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right py-0" aria-labelledby="alertsDropdown">
              <div class="list-group">
                @if( count( Auth::user() -> invitations ) > 0 )
                  @foreach( Auth::user() -> invitations as $invitation )
                    <div class="list-group-item">
                      <div class="row no-gutters align-items-center">
                        <div class="col-2">
                          <i class="fas fa-exclamation text-light"></i>
                        </div>
                        <div class="col-10">
                          <div class="text-dark">Group Invitation</div>
                          <p class="text-muted small mt-1">
                            {!! __('app.notifications.pending_invite', ['name' => htmlspecialchars($invitation->group->name)]) !!}
                          </p>
                          <a class="btn btn-outline-primary btn-sm" href="{{route('group.show', [$invitation->group_id])}}">@lang('app.notifications.pending_invite_go_to_group')</a>
                          <!-- <div class="text-muted small mt-1">2h ago</div> -->
                        </div>
                      </div>
                    </div>
                  @endforeach
                @else
                  <div class="list-group-item text-muted">
                    @lang('app.notifications.no_notifications')
                  </div>
                @endif
              </div>
              {{--
              <div class="list-group-item dropdown-menu-footer">
                <a href="#">@lang('app.notifications.all_notifications')</a>
              </div>
              --}}
            </div>

          </li>

          <li class="nav-item dropdown user-dropdown border border-top-0 border-right-0 border-bottom-0">
            <a class="nav-link dropdown-toggle btn-sm" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <div class="d-flex align-items-center">
                <span class="user-avatar user-avatar-md">
                  <img src="{{auth()->user()->image}}" alt="">
                </span>
                <span>
                  {{ Auth::user() -> name }}
                </span>
              </div>
            </a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="{{route('user.show', [auth()->user()])}}">@lang('user.settings')</a>
              <a class="dropdown-item" href="{{route('logout')}}">@lang('user.logout')</a>
            </div>
          </li>
        </ul>
      </div>
    </div>
  </nav>

  @if( Auth::check() )
    {{-- Breadcrumbs::render() --}}
  @endif
  
  @yield('body')

  <footer class="footer p-4 pt-4 mt-4 bg-white flex-shrink-0 border border-right-0 border-left-0 border-bottom-0">
    <nav class="nav">
      <div class="container text-center">
        <div class="p-2 bd-highlight">
          <a title="@lang('app.privacy_policy')" class="p-2" href="{{ route('privacy-policy') }}">@lang('app.privacy_policy')</a>
          <small class="text-muted">-</small>
          <a title="@lang('app.imprint')" class="p-2" href="{{ route('imprint') }}">@lang('app.imprint')</a>
        </div>
        <div>
          <a title="Twitter" class="p-1" href="#"><i class="fab fa-twitter-square"></i></a>
          <a title="Facebook" class="p-1" href="#"><i class="fab fa-facebook-square"></i></a>
          <a title="Instagram" class="p-1" href="#"><i class="fab fa-instagram"></i></a>
        </div>
      </div>
    </nav>
  </footer>
  <script src="{{ mix('/js/main.js') }}"></script>
  <script src="/js/all.js"></script>
  @yield('scripts')
@endsection

resources/views/layouts/companion_general.blade.php
@extends('layouts.companion')
@section('body')
	@parent
  <div class="container content pt-4">
    <h1 class="h2 mb-2">@yield('title')</h1>
    <div class="card">
      <div class="card-body">
        @yield('content')
      </div>
    </div>
	</div>
@endsection

resources/views/layouts/companion_general_empty.blade.php
@extends('layouts.companion')
@section('body')
  @parent
  <div class="container content pt-4">
    @yield('content')
  </div>
@endsection

resources/views/layouts/companion_group.blade.php
@extends('layouts.companion')
@section('body')

@if( empty( $pendingInvitation ) )
  <div id="app" class="pt-4 bg-white align-items-center">
    <div class="container">
      <div class="row">
        <div class="col-md-6">
          <div class="preview-image" style="background-image: url('{{ $group -> image }}');"></div>
        </div>
        <div class="col-md-6">
          <h2 class="mb-0">{{ $group -> name }}</h2>
          <h5 class="text-muted">
            @if(empty($group -> game_system_name))
              <em>@lang('app.game_system.default.title')</em>
            @else
              {{ $group -> game_system_name . ' ('.__('app.game_system.default.title').')' }}
            @endif
          </h5>
          <ul class="list-inline">
            <!-- <li class="list-inline-item">Göttingen, Deutschland</li> -->
            <!-- <li class="list-inline-item"><a href="{{ route('group.user.index', [$group->id]) }}">{{ sizeof($group->users) }} Player(s)</a></li> -->
          </ul>
          <dl>
            <dt class="mt-2">@lang('group.next_session')</dt>
            <dd>
              <i class="far fa-clock"></i>
                @if( auth()->user() -> isGroupAdmin($group->id) )
                <a href="{{ route('group.edit', [$group]) }}">
                @else
                <a>
                @endif
                  @if($group -> next_session_datetime != null)
                    {{ $group -> next_session_datetime -> toFormattedDateString() }}
                  @else
                    @lang('group.next_session_time_not_set')
                  @endif
                </a>
              <br>
              <i class="far fa-compass"></i> 
                @if( auth()->user() -> isGroupAdmin($group->id) )
                <a href="{{ route('group.edit', [$group]) }}">
                @else
                <a>
                @endif
                  @if( $group -> next_session_location )
                    {{ $group -> next_session_location }}
                  @else
                    @lang('group.next_session_location_not_set')
                  @endif
                </a>
            </dd>
          </dl>
          <p><strong>@lang('group.visibility'):</strong> @lang('group.visibility_status.private')</p>
        </div>
      </div>
    </div>

    <hr>

    <div class="container">
      <nav id="group" class="nav mb-3 w-100">
        <a class="nav-link {{ request()->routeIs('group.show') ? 'active' : '' }} pl-0" href="{{ route('group.show', [$group->id]) }}">@lang('group.menu_overview')</a>
        <a class="nav-link {{ request()->routeIs('group.character.*') ? 'active' : '' }}" href="{{ route('group.characters', [$group->id]) }}">
          @lang('group.menu_characters')
          <small class="text-muted">({{ $activeCharacterCount }})</small>
        </a>
        <a class="nav-link {{ request()->routeIs('group.user*') && !request()->routeIs('group.character*') ? 'active' : '' }}" href="{{ route('group.user.index', [$group->id]) }}">
          @lang('group.menu_users')
          <small class="text-muted">({{sizeof($group->users)}})</small>
        </a>
        @if( $userIsInCurrentGroup )
          <a class="nav-link ml-auto btn btn-outline-primary btn-sm {{ request()->routeIs('group.character*') ? 'active' : '' }}" href="{{ route('group.character', [$group, auth()->user()]) }}"><i class="fas fa-user"></i> @lang('group.menu_my_character')</a>
        @endif
        @if( auth()->user() -> isGroupAdmin($group->id) )
          <a href="{{ route('group.edit', [$group -> id]) }}#general" class="nav-link btn btn-outline-primary btn-sm {{ request()->routeIs('group.edit') ? 'active' : '' }} ml-3"><i class="fas fa-pencil-alt"></i> @lang('group.menu_group_settings')</a>
        @endif
      </nav>
    </div>
  </div>
  <div class="content container pt-4 bg-light">
    @yield('content')
  </div>
@else
    <div class="container content mt-5">
      <div class="row justify-content-md-center">

        <div class="col-md-6">
          <div class="card">
            <div class="card-body d-flex flex-column">
              <div class="d-flex align-items-top">
                <i class="fas fa-shield-alt h1 text-muted pt-2"></i>
                <div class="pl-3">
                  <h2 class="h4 mb-1">Dies ist eine private Gruppe</h2>
                  <p>{!! __('app.notifications.pending_invite_this_group', ['name' => htmlspecialchars($pendingInvitation -> inviter -> name)]) !!}</p>
                  <div class="text-left">
                    <a class="btn btn-success btn-sm" href="{{route('group.invitation.accept', [$group, $pendingInvitation])}}">@lang('app.accept')</a>
                    <a class="btn btn-danger btn-sm" href="{{route('group.invitation.reject', [$group, $pendingInvitation])}}">@lang('app.decline')</a>
                  </div>
                </div>
              </div>
            </div>
          </div>
          
        </div>
      </div>
    </div>
@endif
@endsection

resources/views/layouts/errors.blade.php
@extends('layouts.app')
@section('head')
  <link href="{{ asset('css/public.css') }}" rel="stylesheet">
@endsection
@section('main')
  <div id="app" class="main-wrapper">
    <section class="container error d-flex p-4 align-items-center justify-content-center">
      <div class="text-center">
        <h1 class="text-muted">@yield('title')</h1>
        @yield('message')
      </div>
    </section>
  </div>
@endsection

resources/views/layouts/modal.blade.php
<div class="modal" id="{{$id}}">
  <div class="modal-background" onClick="toggleModal('{{$id}}')"></div>
  <div class="modal-content">
    <div class="box">
      <h3 class="title is-3">{{ $title }}</h3>
      <div class="content">
        {{ $slot }}
      </div>
    </div>
  </div>
  <button class="modal-close is-large" onClick="toggleModal('{{$id}}')" aria-label="close"></button>
</div>

resources/views/layouts/public.blade.php
@extends('layouts.app')
@section('head')
  <link href="{{ asset('css/public.css') }}" rel="stylesheet">
@endsection
@section('main')
<div id="app" class="main-wrapper">

  <header class="auth">
    <h1 class="display-4 brand-font">
      <span class="text-primary">table</span><span class="text-dark">gamers</span>
    </h1>
    <p class="font-weight-normal">@lang('public.brand_subtitle')</p>
  </header>
  
  @yield('content')

  <footer class="footer text-muted"> 
    @lang('public.footer_text', ['link_imprint' => route('imprint'), 'link_privacy_policy' => route('privacy-policy')])
  </footer>
</div>
@endsection